service: graphql-qa-academy

provider:
  name: google
  stage: dev
  runtime: nodejs8
  region: us-central1
  project: qa-ws
  credentials: ~/.gcloud/keyfile.json

plugins:
  - serverless-google-cloudfunctions

package:
  exclude:
    - node_modules/**
    - .gitignore
    - .git/**

functions:
  first:
    handler: myhook
    events:
      - http: path
